/*
    Given 2 strings s and t
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.
*/


// one way is to find the sum of ascii values of both the strings and return the difference like this

/*
    char difference(string s, string t) {
        int s1=0, s2=0;
        for(int i=0;i<s.size();i++)
        {
            s1+=(int)(s[i]);
        }
        for(int i=0;i<t.size();i++)
        {
            s2+=(int)(t[i]);
        }
        return (char)(s2-s1);
    }
*/

#include<iostream>
#include<string>
using namespace std;




// the other way is to find the xor of both the strings. This will return the character which will be extra in second string

char difference(string s, string t)
{
    char c = 0;
       for(int i=0;i<s.size();i++)
       {
           c^=s[i];
       }
       for(int i=0;i<t.size();i++)
       {
           c^=t[i];
       }
        return c;
}

int main()
{
    string s="abcd";
    string t="bdaec";

    char ans=difference(s,t);
    cout<<"The difference between the strings is : "<<ans<<endl;
    return 0;
}